accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={
        'next_page': settings.LOGIN_URL,  # LogoutView CBV에서는 현재 처리되고 있지 않음.
    }),
    url(r'^profile/$', views.profile, name='profile'),
]

askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^weblog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^new/$', views.post_new, name='post_new'),
]

dojo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^sum/(?P<numbers>[\d/]+)/$', views.mysum),
    url(r'^hello/(?P<name>[ㄱ-힣]+)/(?P<age>\d+)/$', views.hello),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
import os
import uuid
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


def min_length_3(value):
    if len(value) < 3:
        raise ValidationError('3글자 이상 입력해주세요.')


def random_upload_to(instance, orig_filename):
    # 파일명을 포함한 모든 경로를 기대
    ext = os.path.splitext(orig_filename)[-1].lower()
    filename = uuid.uuid4().hex + ext
    filepath = os.path.join(filename[:3], filename[3:6], filename[6:9], filename[9:])
    return filepath


class Post(models.Model):
    author = models.CharField(max_length=20, help_text='포스팅 작성자 이름을 입력해주세요.')
    title = models.CharField(max_length=100, validators=[min_length_3])
    content = models.TextField()
    photo = models.ImageField(upload_to=random_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        # '/weblog/{}/'.format(self.id)
        return reverse('blog:post_detail', args=[self.id])
        # return reverse('blog:post_detail', kwargs={'pk': self.id})

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = '내가 원하는 도움말'
        self.fields['email'].help_text = '내가 원하는 Email 도움말'


def check_answer(value):
    if value != 6:
        raise forms.ValidationError('땡~!')

class LoginForm(AuthenticationForm):
    answer = forms.IntegerField(help_text='3+3=?', validators=[check_answer])

blog/forms.py
from django import forms
from .models import Post

# class PostForm(forms.Form):
#   author = forms.CharField()
#   title = forms.CharField()
#   content = forms.CharField()

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

accounts/views.py
from allauth.socialaccount.models import SocialApp
from allauth.socialaccount.templatetags.socialaccount import get_providers
from django.conf import settings
from django.contrib.auth.views import login as auth_login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .forms import SignupForm, LoginForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })


def login(request):
    provider_list = []

    for provider in get_providers():
        try:
            # social_app속성은 provider에는 없는 속성입니다. 그래서 다음과 같이 커스텀 속성을 정의해봤습니다.
            # 세팅된 Provider별 설정현황을 social\_app 속성으로 지정해보겠습니다.
            provider.social_app = SocialApp.objects.get(provider=provider.id, sites=settings.SITE_ID)
        except SocialApp.DoesNotExist:
            # Provider 설정이 없을 경우 .social_app을 None으로 설정
            provider.social_app = None
        provider_list.append(provider)

    return auth_login(request, form_class=LoginForm,
            extra_context={
                'provider_list': provider_list,
            })


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

blog/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.db.models import Q
from .models import Post
from .forms import PostModelForm


def post_list(request):
    qs = Post.objects.all()

    query = request.GET.get('query', '')
    if query:
        condition = Q(title__icontains=query) | Q(content__icontains=query)
        qs = qs.filter(condition)

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'query': query,
    })


def post_detail(request, pk): 
    post = Post.objects.get(pk=pk)  # 이 코드는 설명을 위한 코드일 뿐, 비추코드 !!!
    return render(request, 'blog/post_detail.html', {
        'post': post,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            # form.cleaned_data  # dict타입
            post = form.save()
            return redirect(post)  # post.get_absolute_url() 주소로의 이동을 시도
            # return redirect('blog:post_detail', post.id)
    else:
    # if request.method == 'GET':
        form = PostModelForm()

    return render(request, 'blog/post_form.html', {
        'form': form,
    })

# from django.views.generic import CreateView
# post_new = CreateView.as_view(model=Post, form_class=PostModelForm, success_url='/weblog/')
# post_new = CreateView.as_view(model=Post, form_class=PostModelForm)


@login_required
def post_edit(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        form = PostModelForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            # form.cleaned_data  # dict타입
            post = form.save()
            return redirect(post)  # post.get_absolute_url() 주소로의 이동을 시도
        # return redirect('blog:post_detail', post.id)
    else:
        # if request.method == 'GET':
        form = PostModelForm(instance=post)

    return render(request, 'blog/post_form.html', {
        'form': form,
    })

# from django.views.generic import UpdateView
# post_edit = UpdateView.as_view(model=Post, form_class=PostModelForm)

dojo/views.py
from django.http import HttpResponse
from django.shortcuts import render


def mysum(request, numbers):
    total = sum(int(number or 0) for number in numbers.split('/'))  # generator expression
    return HttpResponse(total)


def hello(request, name, age):
    return HttpResponse('안녕하세요. {}. {}살이시네요.'.format(name, age))

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h1>{{ user }}</h1>

    <img src="{{ user.socialaccount_set.all.first.get_avatar_url }}" />

    {{ user.email }}
    {{ user.date_joined }}
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-block" />
    </form>
{% endblock %}

askdjango/templates/layout.html
{% load bootstrap3 static %}
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>AskDjango 블로그</title>
{# bootstrap_css #}

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" />

<script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
{% bootstrap_javascript %}
{% block extra_head %}{% endblock %}
</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block brand %}
            <a class="navbar-brand" href="#">Ask Django</a>
          {% endblock %}
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            {% block extra_navbar %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if not user.is_authenticated %}
                  <li><a href="{% url "login" %}?next={{ request.path }}">로그인</a></li>
                  <li><a href="{% url "signup" %}">회원가입</a></li>
              {% else %}
                  <li><a href="{% url "profile" %}">프로필</a></li>
                  <li><a href="{% url "logout" %}?next={{ request.path }}">로그아웃</a></li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>AskDjango</h1>
                <p>안녕하세요. 여러분의 파이썬/장고 페이스메이커가 되겠습니다. ;)</p>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block brand %}
    <a class="navbar-brand" href="{% url "blog:post_list" %}">Ask Django 블로그</a>
{% endblock %}

{% block extra_navbar %}
    <li><a href="{% url "blog:post_new" %}">New Post</a></li>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}

    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>{{ post.title }}</h4>
        </div>
        <div class="panel-body">
            {% if post.photo %}
            <img src="{{ post.photo.url }}" style="width: 100px;"/>
            {% endif %}

            {{ post.content|linebreaks }}
        </div>
        <div class="panel-footer">
            <a href="{% url "blog:post_list" %}" class="btn btn-primary">목록</a>
            <a href="{% url "blog:post_edit" post.id %}" class="btn btn-primary">수정</a>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form %}

        <input type="submit" value="저장" class="btn btn-primary btn-block" />
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="query" value="{{ query }}" />
        <input type="submit" value="검색" />
    </form>

    <a href="{% url "blog:post_new" %}">New Post</a>

    <ul>
    {% for post in post_list %}
        <li>
            <a href="{% url "blog:post_detail" post.id %}">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}